src/SatsangApp/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path, include, re_path, reverse
from django.views.generic.base import TemplateView
#from Pages.views import home_View
#from Log_App.views import lgin_view
from django.contrib.auth import views as lgin_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from sponsorApp.views import *
from imsApp.views import *

print(auth_views)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	path('', lgin_view.LoginView.as_view(), {'template_name':"registration/login.html"}),
    #path('login/', lgin_view.LoginView.as_view(), {'template_name':"registration/login.html"}),
    #path('logout/', lgin_view.LogoutView.as_view(),{'template_name':"registration/logged_out.html"}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # url(r'^accounts/reset_password/', auth_views.PasswordResetView.as_view(template_name = "password_reset.html"), name ='reset_password'),
    # url(r'^accounts/reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), name ='password_reset_done'),
    # url(r'^accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"), name ='password_reset_confirm'),
    # url(r'^accounts/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name ='password_reset_complete'),

    url(r'^sponsor/dashboard/$', dashboard_view, name="Sponsor_Dashboard."),
    url(r'^sponsor/sponsordata/$', sponsorView, name="Sponsor_data"),
    url(r'^sponsor/sponsorform/$', sponsor_form_view, name="Sponsor_Form"),
    url(r'^sponsor/display/$', display_view, name="Display_Slide"),
    url(r'^sponsor/team/$', team_group_view, name="Team"),
    url(r'^sponsor/announcer/$', announcer_view, name="Announce_ Slide"),
    url(r'^sponsor/purposecode/$', purposecode_view, name="Purpose_Code"),
    url(r'^ims/imsdata/$', ims_data_table_view, name="IMS_data"),
    url(r'^ims/imsform/$', ims_form_view, name="IMS_form"),
    # Custom app url
    url(r'session_security/', include('session_security.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sponsorApp/models.py
from django.db import models
from django.utils.timezone import get_current_timezone
from datetime import datetime
from datetime import date
from django.utils import timezone
from django.contrib.auth.models import User
# from purposecodeApp.models import Purpose

# User loged in and loged out modal


class LoggedUser(models.Model):
    username = models.CharField(max_length=30, blank=True, null=True)
    loggedIn = models.CharField(max_length=30, blank=True, null=True)
    userAddr = models.CharField(max_length=30, blank=True, null=True)
    userCity = models.CharField(max_length=30, blank=True, null=True)
    userState = models.CharField(max_length=2, blank=True, null=True)
    userLocDict = models.CharField(max_length=500, blank=True, null=True)
    currentTimeStamp = models.DateTimeField(default=datetime.now())

    def __unicode__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.currentTimeStamp = datetime.now()
        return super(LoggedUser, self).save(*args, **kwargs)


class PurposeCode(models.Model):
    Purpose_Code = models.CharField(max_length=120, blank=True, null=True)

    def __str__(self):
        return self.Purpose_Code


class Purpose(models.Model):
    Purpose = models.CharField(max_length=120, blank=True, null=True)
    Purpose_Code = models.ForeignKey(
        PurposeCode, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.Purpose


class DisplayPurpose(models.Model):
    DisplayPurpose = models.CharField(max_length=120, blank=True, null=True)
    Purpose_Code = models.ForeignKey(
        PurposeCode, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.DisplayPurpose


class PurposeIndex(models.Model):
    Purpose_Index = models.CharField(max_length=120, blank=True, null=True)
    Purpose_Code = models.ForeignKey(
        PurposeCode, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.Purpose_Index

# Create your models here.


class purposeData(models.Model):
    currentTimeStamp = models.DateField(auto_now=True, blank=True, null=True)
    Purpose = models.CharField(
        'Purpose', max_length=120, blank=True, null=True)
    Purpose_Code = models.CharField(
        'Purpose Code', max_length=120, blank=True, null=True)
    Purpose_Index = models.IntegerField('Purpose Index', blank=True, null=True)
    DisplayOnPPT = models.CharField(
        'Purpose Title', max_length=120, blank=True, null=True)
    AnnounceAs = models.CharField(
        'Annoucer Note', max_length=120, blank=True, null=True)
    UpdatedDate = models.DateTimeField(
        'Updated Date', auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.Purpose


class Country(models.Model):
    CountryName = models.CharField(
        'State Name', max_length=120, blank=True, null=True)

    def __str__(self):
        return self.CountryName


class State(models.Model):
    StateName = models.CharField(
        'State Name', max_length=120, blank=True, null=True)
    StateAbbr = models.CharField(
        'State Abbr', max_length=120, blank=True, null=True)
    CountryName = models.ForeignKey(
        Country, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.StateName


class City(models.Model):
    City = models.CharField('City', max_length=120, blank=True, null=True)
    StateName = models.ForeignKey(
        State, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.City


class County(models.Model):
    CountyName = models.CharField(
        'County Name', max_length=120, blank=True, null=True)
    City = models.ForeignKey(
        City, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.CountyName


class ZipCode(models.Model):
    ZipCode = models.CharField(
        'Zip Code', max_length=120, blank=True, null=True)
    City = models.ForeignKey(
        City, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.ZipCode

# Create your models here.


class LocationData(models.Model):
    Country = models.CharField(
        'Country', max_length=120, blank=True, null=True)
    StateAbbr = models.CharField(
        'State Abbr', max_length=120, blank=True, null=True)
    StateName = models.CharField(
        'State', max_length=120, blank=True, null=True)
    City = models.CharField('City', max_length=120, blank=True, null=True)
    CountyName = models.CharField(
        'County', max_length=120, blank=True, null=True)
    ZipCode = models.CharField(
        'Zip Code', max_length=120, blank=True, null=True)
    UpdatedDate = models.DateTimeField('Updated Date', auto_now=True)
    #user=models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.StateAbbr

# class PurposeCode(models.Model):
#     Purpose_Code=models.CharField(max_length=120, blank=True, null=True)

#     def __str__(self):
#         return self.Purpose_Code

# class PurposeIndex(models.Model):
#     Purpose_Index=models.CharField(max_length=120, blank=True, null=True)
#     Purpose_Code=models.ForeignKey(PurposeCode, on_delete=models.CASCADE,blank=True, null=True)

#     def __str__(self):
#         return self.Purpose_Index

# class Purpose(models.Model):
#     Purpose=models.CharField(max_length=120, blank=True, null=True)
#     Purpose_Code=models.ForeignKey(PurposeCode, on_delete=models.CASCADE,blank=True, null=True)

#     def __str__(self):
#         return self.Purpose

# class DisplayPurpose(models.Model):
#     DisplayPurpose=models.CharField(max_length=120, blank=True, null=True)
#     Purpose_Code=models.ForeignKey(PurposeCode, on_delete=models.CASCADE,blank=True, null=True)

#     def __str__(self):
#         return self.DisplayPurpose


# Create your models here.
class SponsorsData(models.Model):
    COUNTRY_CHOICES = (
        ('1', 'INDIA'),
        ('2', 'USA'),
    )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    YESNO_CHOICES = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    CITY_CHOICES = (
        ('1', 'Atlanta'),
        ('2', 'Cumming'),
        ('3', 'Alpharetta')
    )
    STATE_CHOICES = (
        ('1', 'GA'),
        ('2', 'FL')
    )
    PURPOSE_CHOICES = (
        ('ravi sabha', 'Ravi Sabha'),
        ('all ravi sabha', 'All Ravi Sabha'),
        ('grand ravi sabha', 'Grand Ravi Sabha'),
    )
    FirstName = models.CharField(
        'First Name', max_length=120, blank=True, null=True)
    MiddleName = models.CharField(
        'Middle Name', max_length=120, blank=True, null=True)
    LastName = models.CharField(
        'Last Name', max_length=120, blank=True, null=True)
    MemberId = models.DecimalField(
        'Member Id', default=0, max_digits=20, decimal_places=0, blank=True, null=True)
    Gender = models.CharField(
        'Gender', max_length=1, blank=True, null=True, choices=GENDER_CHOICES, default='M')
    ZipCode = models.DecimalField(
        'Zip Code', max_digits=20, decimal_places=0, blank=True, null=True)
    #Country=models.ForeignKey(Country, on_delete=models.CASCADE,blank=True, null=True)
    #State=models.ForeignKey(State, on_delete=models.CASCADE,blank=True, null=True)
    #City=models.ForeignKey(City, on_delete=models.CASCADE,blank=True, null=True)
    # , choices=COUNTRY_CHOICES, default='US'), choices=STATE_CHOICES, default='Georgia'), choices=CITY_CHOICES, default='')
    City = models.CharField('City', max_length=120, blank=True, null=True)
    State = models.CharField('State', max_length=120, blank=True, null=True)
    Country = models.CharField(
        'Country', max_length=120, blank=True, null=True)
    #Purpose=models.CharField('Purpose',max_length=120,blank=True, null=True, choices=PURPOSE_CHOICES, default='NA')
    Purpose = models.ForeignKey(
        Purpose, on_delete=models.CASCADE, blank=True, null=True)
    Purpose_Code = models.CharField(
        'Purpose Code', max_length=120, blank=True, null=True)
    PurposeIndex = models.DecimalField(
        'Purpose Index', default=0, max_digits=20, decimal_places=0, blank=True, null=True)
    #Purpose_Code=models.ForeignKey(PurposeCode, on_delete=models.CASCADE,blank=True, null=True)
    #PurposeIndex=models.ForeignKey(PurposeIndex, on_delete=models.CASCADE,blank=True, null=True)
    Memo = models.CharField('Announcer Note(s)', default='NA',
                            blank=True, null=True, max_length=200)
    currentTimeStamp = models.DateTimeField(auto_now_add=True)
    sponsorshipDate = models.DateField(
        'Sponsor Date', default=timezone.now, blank=True, null=True)
    DisplayOnPPT = models.CharField(
        'PPT', max_length=3, blank=True, null=True, choices=YESNO_CHOICES, default='Y')
    Announce = models.CharField(
        'Announce', max_length=3, blank=True, null=True, choices=YESNO_CHOICES, default='Y')
    amountReceived = models.CharField(
        'Amount Received', max_length=3, blank=True, null=True, choices=YESNO_CHOICES, default='Y')
    EnteredBy = models.CharField(
        'Entered By', max_length=120, blank=True, null=True)
    UpdatedDate = models.DateTimeField('Updated Date', auto_now=True)
    user = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return ('%s (%s %s)') % (self.id, self.FirstName, self.LastName)

    def save(self, *args, **kwargs):
        self.FirstName = self.FirstName.title()
        if self.MiddleName is not None:
            self.MiddleName = self.MiddleName.title()
        self.LastName = self.LastName.title()
        self.City = self.City.title()
        self.State = self.State.upper()
        self.Memo = self.Memo.title()
        return super(SponsorsData, self).save(*args, **kwargs)


class searchData(models.Model):
    inputSearch = models.CharField(

src/sponsorApp/forms.py
from django import forms
from django.forms import Textarea
from .models import *
# SponsorsData, purposeData
from datetime import datetime as dt

# Assign date input type
class DateInput(forms.DateInput):
    input_type = 'date'

#Create a form for sponsor
class SponsorForm(forms.ModelForm):
    currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d')
    sponsorshipDate = forms.DateField(widget=DateInput, initial=currentDt)
    Memo = forms.CharField(max_length=150,widget=forms.Textarea(),help_text='Enter Memo/Announce Note.')
    class Meta:
        lst = []
        model = SponsorsData
        # Remove field from the form
        #exclude = ['Country','City', 'State']
        for x in SponsorsData._meta.fields:
            if x.name != 'currentTimeStamp' and x.name != 'UpdatedDate':
                lst.append(x.name)
        fields = lst
        wLst = ''
        #widget = {
        #    fields: forms.TextInput(attrs={'class': 'gp-input gp-border'}),
        #}
    def __init__(self, *args, **kwargs):
        super(SponsorForm, self).__init__(*args, **kwargs)
        currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d')
        for field in self.fields:
            #if field=='Gender':
            #    clsStr='gp-radio gp-boarder'
            #    typStr='radio'
            #else:
            if field != 'MiddleName':
                self.fields[field].required = True
            clsStr='gp-input gp-boarder spFormInput'
            typStr='text'
            plcStr=field   
            if field=='sponsorshipDate':
                self.fields[field].initial=currentDt
            self.fields[field].widget.attrs.update({'class': clsStr, 'type': typStr, 'placeholder':plcStr, 'style':'text-transform: capitalize'})
    
    # def clean(self, *args, **kwargs):
    #     for field in self.fields:
    #         self.fields[field] = self.fields[field].capitalize()

#Update sponsor
class UpdateSponsorForm(forms.ModelForm):
    currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d').strftime('%m/%d/%Y')
    sponsorshipDate = forms.DateField(widget=DateInput, initial=currentDt)
    Memo = forms.CharField(max_length=150,widget=forms.Textarea(),help_text='Enter Memo/Announce Note.')
    class Meta:
        lst = []
        model = SponsorsData
        # Remove field from the form
        #exclude = ['Country','City', 'State']
        for x in SponsorsData._meta.fields:
            if x.name != 'currentTimeStamp' and x.name != 'UpdatedDate':
                lst.append(x.name)
        fields = lst
        wLst = ''
        #widget = {
        #    fields: forms.TextInput(attrs={'class': 'gp-input gp-border'}),
        #}
    def __init__(self, *args, **kwargs):
        super(UpdateSponsorForm, self).__init__(*args, **kwargs)
        currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d').strftime('%m/%d/%Y')    
        for field in self.fields:
            #if field=='Gender':
            #    clsStr='gp-radio gp-boarder'
            #    typStr='radio'
            #else:
            #self.fields[field].required = True
            clsStr='gp-input gp-boarder spFormInput'
            typStr='text'
            plcStr=field   
            if field=='sponsorshipDate':
                self.fields[field].initial=currentDt
            self.fields[field].widget.attrs.update({'class': clsStr, 'type': typStr, 'placeholder':plcStr})

    # def clean(self, *args, **kwargs):
    #     for field in self.fields:
    #         self.fields[field] = self.fields[field].capitalize()

#Create a form for purpose data
class purposeForm(forms.ModelForm):
    # currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d')
    # sponsorshipDate = forms.DateField(widget=DateInput, initial=currentDt)
    # Memo = forms.CharField(max_length=150,widget=forms.Textarea(),help_text='Enter Memo/Announce Note.')
    class Meta:
        lst = []
        model = purposeData
        for x in purposeData._meta.fields:
            if x.name != 'currentTimeStamp' and x.name != 'UpdatedDate':
                lst.append(x.name)
        fields = lst
        wLst = ''
        #widget = {
        #    fields: forms.TextInput(attrs={'class': 'gp-input gp-border'}),
        #}
    def __init__(self, *args, **kwargs):
        super(purposeForm, self).__init__(*args, **kwargs)
        currentDt = dt.strptime(str(dt.today()).split(' ')[0], '%Y-%m-%d')
        for field in self.fields:
            clsStr='gp-input gp-boarder spFormInput'
            typStr='text'
            plcStr=field
            self.fields[field].widget.attrs.update({'class': clsStr, 'type': typStr, 'placeholder':plcStr, 'style':'text-transform: capitalize'})
    
    # def clean(self, *args, **kwargs):
    #     for field in self.fields:
    #         self.fields[field] = self.fields[field].capitalize()

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block titleName %}Satsang Seva{% endblock %}</title>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js'></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://www.w3schools.com/lib/w3.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img\icons\Master\svg\ico\apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img\icons\Master\ico\favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img\icons\Master\ico\favicon-16x16.png' %}">
  <script></script>
  <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'gp.css' %}" type="text/css" />
  <style>
  </style>
</head>
{% spaceless %}
<body>
  <header>
    {% include 'navBar.html' %}
  </header>
  <div class="main" id="allContainer" style="height: min(94.5vh, 1940px);">
    <div class="gp-animate-zoom gp-container gp-align-left gp-panel gp-card gp-white gp-text-black gp-hide">This is a notification!
    </div>
    {% block content %}<div class="gp-display-middle gp-card gp-padding-64">You are not Loged in. Please Login First.
    </div>{% endblock content %}
  </div>
  {% include 'session_security/all.html' %}
  {% block footer %}
  <!-- Footer -->
  <footer class="gp-center gp-black gp-padding-64 gp-opacity gp-hover-opacity-off" id="id01">
    <a href="#hm" class="gp-button gp-light-grey"><i class="fa fa-arrow-up gp-margin-right"></i>To the top</a>
    <div class="gp-xlarge gp-section">
      <i class="fa fa-facebook-official gp-hover-opacity"></i>
      <i class="fa fa-instagram gp-hover-opacity"></i>
      <i class="fa fa-snapchat gp-hover-opacity"></i>
      <i class="fa fa-pinterest-p gp-hover-opacity"></i>
      <i class="fa fa-twitter gp-hover-opacity"></i>
      <i class="fa fa-linkedin gp-hover-opacity"></i>
    </div>
    <p>CSS Library used from <a href="" title="gp" target="_blank" class="gp-hover-text-green">bootstrap & gp-Css</a>
    </p>
  </footer>
  {% endblock footer %}
  <script type="text/javascript" src="{% static 'main.js' %}"> var auth = "{{user.is_authenticated}}"; </script>
<script>
  '{% if user.is_authenticated %}'
  sessionSecurity.activity();
  window.addEventListener("load", function () { window.scrollTo(0, 0); });
  function bigbar_open() {
    document.getElementById("menu").style.display = "none";
    document.getElementById("allContainer").style.marginLeft = "200px";
    '{% if request.get_full_path == "/sponsor/sponsorform/" %}'
    document.getElementById("sponsorModal").style.marginLeft = "200px";
    '{% endif %}'
    document.getElementById("myBigSidebar").style.display = "block";
  }
  function bigbar_close() {
    document.getElementById("menu").style.display = "block";
    document.getElementById("allContainer").style.marginLeft = "0%";
    '{% if request.get_full_path == "/sponsor/sponsorform/" %}'
    document.getElementById("sponsorModal").style.marginLeft = "0%";
    '{% endif %}'
    document.getElementById("myBigSidebar").style.display = "none";
  }
  var mySidebar = document.getElementById("ssSB");
  function bar_open() {
    if (mySidebar.style.display === 'block') {
      mySidebar.style.display = 'none';
    } else {
      mySidebar.style.display = 'block';
    }
  }
  function bar_close() {
    mySidebar.style.display = "none";
  }
  var width = window.innerWidth
  || document.documentElement.clientWidth
  || document.body.clientWidth;
  var height = window.innerHeight
  || document.documentElement.clientHeight
  || document.body.clientHeight;
  '{% if request.get_full_path == "/sponsor/dashboard/" or request.get_full_path == "/sponsor/display/" %}'
  var locCity, LocState;
  locCity = '{{ userCity }}';
  locState = '{{ userState }}';
  $('#barTitle').text('SPONSOR');
  '{% endif %}'
  '{% if request.get_full_path == "/ims/imsdata/" or request.get_full_path == "/ims/imsform/" %}'
  $('#barTitle').text('IMS APP');
  '{% endif %}'
  '{% if request.get_full_path != "/accounts/logout/" and request.get_full_path != "/accounts/login/" and request.get_full_path != "/sponsor/display/" %}'
  document.addEventListener('DOMContentLoaded', function () {
    let dashboardref = document.querySelector('.dashboarduserinfo');
    let ul1 = document.querySelector('#userList');
    let mnContainer = document.querySelector('#allContainer');
    var loc = window.location;
    var pname = loc.pathname;
    var uLio1, uLio;
    var wsStart = 'ws://';
    if (loc.protocol == 'https:') {
      wsStart = 'wss://';
    }
    const alertSocket = new ReconnectingWebSocket(
      wsStart
      + loc.host
      + loc.pathname
    );
    alertSocket.onmessage = function (e) {
      var setTm;
      var msgIn = JSON.parse(e.data);
      if (msgIn.Desc === 'User Log In/Out.') {

        if ('{{ user.first_name }}' !== msgIn.username) {
          var el = document.createElement("li");
          $('#id_' + msgIn.username).remove();
          var nodeLi, nodeSpan;
          $(ul1).prepend(msgIn.uStatusList);
          $(mnContainer).append(msgIn.uStatus);
        }
      } else if (msgIn.Desc === 'Sponsor Added/Updated') {
        $('#spTotal').text(msgIn.spTotal);
        $('#spTodayTotal').text(msgIn.spTodayTotal);
        $('#dbSpTableBody').prepend(msgIn.spListHTML);
        $(mnContainer).append(msgIn.spStatusHTML);
      }
      setTimeout(function () {
        if ($('#appStatus').length > 0) {
          $('#appStatus').remove();
        }
      }, 3000);
    }
  });
  '{% endif %}'
  '{{ request.get_full_path }}'
  '{% if request.get_full_path == "/sponsor/sponsordata/" or request.get_full_path == "/sponsor/sponsorform/"  or request.get_full_path == "/sponsor/sharedSponsorform/" or request.get_full_path == "ims/imsform/" %}'
  $("#id_ZipCode").change(function () {
    var url = "{{ request.path }}";
    var zipcodeId = $(this).val();
    $.ajax({
      type: "POST",
      url: url,
      data: {
        csrfmiddlewaretoken: '{{ csrf_token }}',
        zipcode: zipcodeId,
      },
      success: function (data) {
        if (data.is_taken) {
          alert("Location not available.");
        } else {
          $.each(data, function (key, value) {
            $("#" + key).val(value);
            var el = document.getElementById(key);
            if (value == 'NA') {
              el.readOnly = false;
            } else {
              el.readOnly = true;
            }
          });
        }
      }
    });
  });
  $("#id_Purpose").change(function () {
    var url = "{{ request.path }}";
    var purposeId = $(this).val();
    $.ajax({
      type: "POST",
      url: url,
      data: {
        csrfmiddlewaretoken: '{{ csrf_token }}',
        purpose: purposeId,
      },
      success: function (data) {
        if (data.is_taken) {
          alert("Location not available.");
        } else {
          $.each(data, function (key, value) {
            $.each(value, function (k, v) {
              if (k === 'fields') {
                console.log();
                $("#id_Purpose_Code").val(v['Purpose_Code']);
                $("#id_PurposeIndex").val(v['Purpose_Index']);
                $("#id_Memo").val(v['AnnounceAs']);
              }
            });
          });
        }
      },
    });
  });
  $(function () {
    var id;
    var lstValue = [];
    function getListValue(val) {
      var vl, vlInd;
      vl = val;
      id = id;
      if ((val.indexOf(",")) !== -1) {
        vlInd = (val).lastIndexOf(",") + 1;
      } else if ((val.indexOf(" ")) !== -1) {
        vlInd = (val).lastIndexOf(" ") + 1;
      } else if ((val.indexOf("&")) !== -1) {
        vlInd = (val).lastIndexOf("&") + 1;
      } else {
        vlInd = 0;
      };
      vl = (val).substr(vlInd);
      vl = vl.trim();
      $.ajax({
        url: "{{ request.path }}",
        type: "POST",
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          lst: id + '-' + vl,
        },
        success: function (data) {
          var result = [];
          data = JSON.parse(data);
          len = data.length;
          for (i = 0; i < len; i++) {
            result.push({
              label: data[i],
              value: data[i]
            });
            lstValue[i] = data[i];
          }
          return lstValue;
        },
      });
    };
    function split(val) {
      return val.split(/,\s*/);
    }
    function extractLast(term) {
      return split(term).pop();
    }
    $("input.spFormInput")
      .on("keydown", function (event) {
        id = this.id;
        if (event.keyCode === $.ui.keyCode.TAB &&
          $(this).autocomplete("instance").menu.active) {
          event.preventDefault();
        }
      })
      .autocomplete({
        minLength: 0,
        source: function (request, response) {
          getListValue(request.term);
          response($.ui.autocomplete.filter(
            lstValue, extractLast(request.term)));
        },
        focus: function () {
          return false;
        },
        select: function (event, ui) {
          var terms = split(this.value);
          terms.pop();
          terms.push(ui.item.value);
          terms.push("");
          this.value = terms.join(", ");
          return false;
        }
      });
  });
  '{% endif %}'
  const getUA = () => {
    let device = "Unknown";
    const ua = {
      "Generic Linux": /Linux/i,
      "Android": /Android/i,
      "BlackBerry": /BlackBerry/i,
      "Bluebird": /EF500/i,
      "Chrome OS": /CrOS/i,
      "Datalogic": /DL-AXIS/i,
      "Honeywell": /CT50/i,
      "iPad": /iPad/i,
      "iPhone": /iPhone/i,
      "iPod": /iPod/i,
      "macOS": /Macintosh/i,
      "Windows": /IEMobile|Windows/i,
      "Zebra": /TC70|TC55/i,
    }
    Object.keys(ua).map(v => navigator.userAgent.match(ua[v]) && (device = v));
    return device;
  }
  '{% endif %}'
  '{% block script %}'
  '{% endblock script %}'
</script>

</body>
{% endspaceless %}
</html>